### ISSUE TITLE
Add the option of using different config files

### ISSUE THREAD

**Issue by dostuffthatmatters** [tum-esm/em27-retrieval-pipeline#98]
Whenever using the CLI, it should ask which config to use in case it finds multiple configs like `*.config.json` in the config directory.

**Comment by cfleur** [comment]
How about specifying a different config directory all together, is that in the scope of this issue?

**Comment by dostuffthatmatters** [comment]
Fulfilled by #108

**Comment by dostuffthatmatters** [comment]
Yes, that is fine. Keeping different configs in different directories can achieve the same thing. The goal was to quickly switch between different retrieval setups: before that was only possible by cloning repo multiple times or renaming the config files on any switch.
